### ISSUE TITLE
Promise rejection when running track-investments

### ISSUE THREAD

**Issue by faultoverload** [psybers/actual-helpers#1]
I have been able to run the sync-bank,kbb, and zestimate scripts but I get this error with the track-investments.

I have one SimpleFIN synced account that I added "calcInvestment" to the notes.
```
connect
open file
Loaded spreadsheet from cache (14787 items)
Syncing since 2024-07-01T19:53:43.236Z-0000-a172f8989c62ff17 2 (attempt: 0)
Got messages from server 1
node:internal/process/promises:389
      new UnhandledPromiseRejection(reason);
      ^

UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "#<Object>".
    at throwUnhandledRejectionsMode (node:internal/process/promises:389:7)
    at processPromiseRejections (node:internal/process/promises:470:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:32) {
  code: 'ERR_UNHANDLED_REJECTION'
}

Node.js v22.3.0
```

**Comment by psybers** [comment]
Can you try running `node --trace-warnings track-investments.js` to see if we get a useful stack trace?

**Comment by faultoverload** [comment]
That doesn't appear to have change the output.

```
connect
open file
Loaded spreadsheet from cache (14787 items)
Syncing since 2024-07-01T19:56:28.349Z-0000-a172f8989c62ff17 0 (attempt: 0)
Got messages from server 1
node:internal/process/promises:389
      new UnhandledPromiseRejection(reason);
      ^

UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "#<Object>".
    at throwUnhandledRejectionsMode (node:internal/process/promises:389:7)
    at processPromiseRejections (node:internal/process/promises:470:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:32) {
  code: 'ERR_UNHANDLED_REJECTION'
}

Node.js v22.3.0
```

**Comment by psybers** [comment]
@faultoverload I also updated the code to add more logging, could you pull and see if that gives a trace?

**Comment by psybers** [comment]
@faultoverload This might have been because you renamed the account.  Did you rename the account from what SimpleFIN originally provided?

I hit that issue with one of my accounts.  I fixed the crash, but unfortunately for now I can't get it to work.  There is a PR in Actual that needs merged before this can work with accounts that were renamed.

**Comment by faultoverload** [comment]
Hey, I don't think I renamed anything in simplefin but the account name in
Actual doesn't match with Simplefin.

I tried running the updated code you added but I was actually getting
errors for all the scripts after that. Tested on my local install as well
as a docker container running node.

**Comment by psybers** [comment]
@faultoverload Did you update the packages, `npm update`? It needs the latest Actual API.

But yes if the name does not match that was why you were previously getting an error.  As of right now, the error should be silenced but it will not update it.  After one of my PRs is merged in and a new Actual release happens I'll update these scripts and it should start working.

**Comment by psybers** [comment]
@faultoverload You need to run `npm update` to get the latest Actual API.  Otherwise, you get APIErrors because the API you are using does not match the server's API.

Since you are doing it via Docker images, you will need to rebuild the Docker image.

**Comment by psybers** [comment]
Ok actually this might be my code.  It looks like the API was changed to require a category ID and I do not provide one.  Let me try fixing this.

**Comment by psybers** [comment]
@faultoverload If you can, please pull the latest.  This should fix your issues.  You might need to set some new environment variables in your `.env` file:

```env
# optional, name of the payee for added interest transactions
INVESTMENT_PAYEE_NAME="Investment"
# optional, name of the cateogry group for added investment tracking transactions
INVESTMENT_CATEGORY_GROUP_NAME="Income"
# optional, name of the category for added investment tracking transactions
INVESTMENT_CATEGORY_NAME="Investment"
```

**Comment by faultoverload** [comment]
I pulled your new code and rebuilt the container and after a bit of fussing about it appears to be working correctly.

Is it possible to allow us to declare the SimpleFIN token through the .var file because having to type it into the console during the first run breaks the automation with Docker.

**Comment by psybers** [comment]
The token is only good for one use, so no matter how you do it you must save the result.  You could mount the path into your Docker image, so that the file that saves the login token is persisted.

I'm going to close this issue since you got it working.

**Comment by psybers** [comment]
That said I can maybe get it so you can stuff the resulting token into an ENV...

**Comment by psybers** [comment]
Pull the latest.  Now when you give it your setup token it will print the credentials (and store to the file).  If you want, you can stick that into an ENV and it will use that instead of the file.

**Comment by faultoverload** [comment]
Thanks! That did the trick. I submitted my code as a pull request in case anyone else wants to use Docker for this project.
