### ISSUE TITLE
Add Docker Containers to a Registry

### ISSUE THREAD

**Issue by mcDevnagh** [psybers/actual-helpers#13]
Instead of needing to build the Docker Container locally, as per the [README](https://github.com/psybers/actual-helpers?tab=readme-ov-file#setup-with-docker), GitHub actions can build it and publish it to the [GitHub Container Registry](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry).

**Comment by psybers** [comment]
Good idea!  This is now set up for the repo.

I added a docker-compose file that utilizes it.
