### ISSUE TITLE
Allow to specify env file on calling script

### ISSUE THREAD

**Issue by soloam** [psybers/actual-helpers#14]
Hello, I use your scripts but I have multiple files, to sync them all I need to have one clone of you repo for each file because of the sync id! It would be nice if it would be possible to manipulate the env file to run so that I could call the same scrip with diferent .env files.

Thank You
Best Regards

**Comment by psybers** [comment]
Unless you have an idea of how to directly support this, I do not.  I would recommend using something like this:

https://dotenvx.com/docs/quickstart/environments
