### ISSUE TITLE
Possible User error but could not get remote files

### ISSUE THREAD

**Issue by jrgiacone** [psybers/actual-helpers#2]
I tried setting it up the best I could including pulling sync I'd from budget settings but getting this error:

`Unhandled Rejection at: Promise Promise {
  <rejected> Error: Could not get remote files
      at handlers.api/download-budget (/home/jrgiacone/actual-helpers/node_modules/@actual-app/api/dist/app/bundle.api.js:29613:31)
} reason: Error: Could not get remote files
    at handlers.api/download-budget (/home/jrgiacone/actual-helpers/node_modules/@actual-app/api/dist/app/bundle.api.js:29613:31)
Error: Could not get remote files
    at handlers.api/download-budget (/home/jrgiacone/actual-helpers/node_modules/@actual-app/api/dist/app/bundle.api.js:29613:31)
Unhandled Rejection at: Promise Promise {
  <rejected> Error: Could not get remote files
      at handlers.api/download-budget (/home/jrgiacone/actual-helpers/node_modules/@actual-app/api/dist/app/bundle.api.js:29613:31)
} reason: Error: Could not get remote files
    at handlers.api/download-budget (/home/jrgiacone/actual-helpers/node_modules/@actual-app/api/dist/app/bundle.api.js:29613:31)
Error: Could not get remote files
    at handlers.api/download-budget (/home/jrgiacone/actual-helpers/node_modules/@actual-app/api/dist/app/bundle.api.js:29613:31)`

Note I'm hosting this on a raspberry pi in docker and trying to run the scripts on the same pi. Using same IP I would access from off the pi, locahost does not work either, https is set up and working

**Comment by psybers** [comment]
That is an odd one, but may be within Actual's API...

If you had the wrong URL you would get a network error.  If you had the wrong password, it would say unauthorized.  If you had the wrong sync ID, it would say budget not found.

This specific point of error in their code indicates it just returned 0 budget files.  So somehow it found it (and did not throw an error) yet did not return it!  I'll have to dig through their code and see what is happening.

**Comment by jrgiacone** [comment]
> That is an odd one, but may be within Actual's API...
> 
> If you had the wrong URL you would get a network error. If you had the wrong password, it would say unauthorized. If you had the wrong sync ID, it would say budget not found.
> 
> This specific point of error in their code indicates it just returned 0 budget files. So somehow it found it (and did not throw an error) yet did not return it! I'll have to dig through their code and see what is happening.

I appreciate it! I have actual docker-compose in /home/jrgiacone/actual and this repo as shown above, if it’s running on the same pi that actual server is on should I still be able to use the ip of the pi:5006? 

I put in the IP
My server password
Copied budget sync Id
Commented out encryption and left the rest default

**Comment by jrgiacone** [comment]
I have to be doing something wrong no matter the IP its the same error, i have node 22

**Comment by armanckeser** [comment]
I get the same error on a curiously similar setup. But I believe mine is a networking problem as I can't seem to send a curl to the backend. Will investigate more, side note are you using latest or edge for actual server?

**Comment by jrgiacone** [comment]
> I get the same error on a curiously similar setup. But I believe mine is a networking problem as I can't seem to send a curl to the backend. Will investigate more, side note are you using latest or edge for actual server?

Latest currently verbatim from the docker file provided on actual docs

**Comment by virtualJonesie** [comment]
I am experiencing the same issue. I've tried tweaking the .env file, but continually get the following errors:

connect
open file
Unhandled Rejection at: Promise Promise {
  <rejected> Error: Could not get remote files
      at handlers.api/download-budget (/home/dave/actual-helpers/node_modules/@actual-app/api/dist/app/bundle.api.js:29613:31)
} reason: Error: Could not get remote files
    at handlers.api/download-budget (/home/dave/actual-helpers/node_modules/@actual-app/api/dist/app/bundle.api.js:29613:31)
Error: Could not get remote files
    at handlers.api/download-budget (/home/dave/actual-helpers/node_modules/@actual-app/api/dist/app/bundle.api.js:29613:31)

**Comment by jrgiacone** [comment]
It’s at least a little validating that I’m not the only one

**Comment by virtualJonesie** [comment]
I'm self-hosting on my Synology NAS via Docker, and I'm using a self-signed SSL certificate. Could that be the issue? That API doesn't trust the cert?

**Comment by psybers** [comment]
> I'm self-hosting on my Synology NAS via Docker, and I'm using a self-signed SSL certificate. Could that be the issue? That API doesn't trust the cert?

I don't know, maybe. But if that was the issue I would hope Actual's API would throw some more informative error indicating such.

**Comment by jrgiacone** [comment]
> > I'm self-hosting on my Synology NAS via Docker, and I'm using a self-signed SSL certificate. Could that be the issue? That API doesn't trust the cert?
> 
> I don't know, maybe. But if that was the issue I would hope Actual's API would throw some more informative error indicating such.

Same in using the self signed openssl from the instructions on actual wiki… if that’s what we are talking about

**Comment by psybers** [comment]
Ok so that is probably the issue.

So we need to set this up so that it accepts your self-signed cert.

Try pulling the latest and rebuilding your Docker image.

**Comment by jrgiacone** [comment]
> Ok so that is probably the issue.
> 
> So we need to set this up so that it accepts your self-signed cert.
> 
> Try pulling the latest and rebuilding your Docker image.

Will this work for non docker helpers I posted the original issue but it wasn’t via the docker file. Only actual is from docker?

**Comment by psybers** [comment]
If you are not using docker, you need to set the environment variable `NODE_TLS_REJECT_UNAUTHORIZED=0`.

**Comment by armanckeser** [comment]
Mine was a networking problem, I connected the actual helper and actual containers through a bridge and used the url `http://Actual:8080` as my actual url, and that seems to have fixed it. `Actual` is the container name for the server and `8080` was my actual port.

**Comment by jrgiacone** [comment]
> If you are not using docker, you need to set the environment variable `NODE_TLS_REJECT_UNAUTHORIZED=0`.

That was the perfect fix, maybe it would be good to have that as an option in the readme. I will update the discord issue for anyone else that searches! Would you like me to close this or leave it open

**Comment by virtualJonesie** [comment]
This seems to have solve the issue for me as well. Thanks for the quick response and updated code!

**Comment by virtualJonesie** [comment]
I am experiencing the same issue with another project: actual-ai. I see the changes to the Dockerfile and .env files. Were there other changes you needed to make to resolve this? I'm trying to provide guidance to the owner of the actual-ai project to resolve this same issue.

Thanks!

**Comment by psybers** [comment]
> I am experiencing the same issue with another project: actual-ai. I see the changes to the Dockerfile and .env files. Were there other changes you needed to make to resolve this? I'm trying to provide guidance to the owner of the actual-ai project to resolve this same issue.
> 
> Thanks!

The environment variable was the only thing needed.
